name: Protect Master

on:
  check_run:
    types: [completed]
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [build_finished]

jobs:
  check-bitrise:
    runs-on: ubuntu-latest
    steps:
      - name: Extract source branch name
        id: branch
        run: echo "SOURCE_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Check if branch starts with rn/
        id: check_prefix
        run: |
          if [[ "${{ env.SOURCE_BRANCH }}" == rn/* ]]; then
            echo "IS_RN_BRANCH=true" >> $GITHUB_ENV
          else
            echo "IS_RN_BRANCH=false" >> $GITHUB_ENV
          fi

      - name: Succeed immediately if branch does not start with rn/
        if: env.IS_RN_BRANCH == 'false'
        run: echo "Skipping Bitrise check since branch does not start with rn/."

      - name: Check Bitrise status (without waiting)
        if: env.IS_RN_BRANCH == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const ref = context.payload.pull_request.head.sha;
            
            const { data: checks } = await github.rest.checks.listForRef({
              owner,
              repo,
              ref
            });

            const bitriseCheck = checks.check_runs.find(check =>
              check.name.toLowerCase().includes('ci/bitrise')
            );

            console.log("Bitrise check: " + console.log(JSON.stringify(bitriseCheck, null, 2)));
            if (!bitriseCheck) {
              console.log("Bitrise check not found. Branch is rn/ so failing");
              core.setFailed("Bitrise check not present.");
            }

            if (bitriseCheck.conclusion === 'success') {
              console.log("✅ Bitrise check passed.");
            } else {
              core.setFailed("❌ Bitrise check failed.");
            } 
